pipeline {
    agent any
    
    stages {
        stage('Install Dependencies') {
            steps {
                script {
                    sh 'sudo apt-get update && sudo apt-get install -y azure-cli'
                }
            }
        }
        stage('Verify Azure CLI') {
            steps {
                sh 'az --version'
            }
        }
        stage('build') {
            steps {
                withCredentials([azureServicePrincipal('AZURE_CREDENTIALS')]) {
                    sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                }
            }
        }
    }
}